version: "2"
services:
  server:
    image: gabi102/repositorygabi:server
    links:
      - db
    depends_on:
      - db
    ports:
      - "5000:5000"
    tty: true
    stdin_open: true

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  admin:
    image: gabi102/repositorygabi:admin
    links:
      - db
    depends_on:
      - db
    ports:
      - "5010:5010"
    tty: true
    stdin_open: true
